# Fabric Properties
  minecraft_version = 1.21.5
  yarn_mappings = 1.21.5+build.1

# Fabric Mod Metadata
  minecraft_dependency = 1.21.5
  carpet_dependency = >=1.4.169

# Mod Dependency
  carpet_core_version = 1.21.5-1.4.169+v250325
  g4mespeed_version = 1.4.11-mc1.21.5
  lithium_version = curse.maven:lithium-360438:6658792
  malilib_version = maven.modrinth:malilib:0.24.3
  mod_menu_version = 14.0.1
fabric_api_version = 0.128.2+1.21.5
