# Fabric Properties
  minecraft_version = 1.20.4
  yarn_mappings = 1.20.4+build.3

# Fabric Mod Metadata
  minecraft_dependency = 1.20.4
  carpet_dependency = >=1.4.128

# Mod Dependency
  carpet_core_version = 1.20.3-1.4.128+v231205
  g4mespeed_version = 1.4.6-mc1.20.4
  lithium_version = mc1.20.4-0.12.1
  malilib_version = 1.20.4:0.18.3
  mod_menu_version = 9.2.0
fabric_api_version=0.97.3+1.20.4
